/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/soapBar1.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/soapBar1.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Soap_Bar.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload('/soapBar1.glb');
