/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/soapBar1.gltf --types --transform 
Files: public/model/soapBar1.gltf [2.6KB] > /Users/owen/repos/cyphe-3d-shop/soapBar1-transformed.glb [52.47KB] (-1918%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.MeshStandardMaterial>;
};

export function Model(
  props: JSX.IntrinsicElements['group'] & { dispose?: (() => void) | null },
) {
  const { nodes, materials } = useGLTF(
    '/model/soapBar1-transformed.glb',
  ) as GLTFResult;
  return (
    /* eslint-disable react/no-unknown-property */
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Soap_Bar.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload('/model/soapBar1-transformed.glb');
