/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/SoapBar2.glb --types --tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.MeshStandardMaterial>;
};

export function Model(
  props: JSX.IntrinsicElements['group'] & { dispose?: (() => void) | null },
) {
  const { nodes, materials } = useGLTF('/model/SoapBar2.glb') as GLTFResult;
  return (
    /* eslint-disable react/no-unknown-property */
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Klime_Soapbar.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload('/model/SoapBar2.glb');
